import {
  Icon,
  IconAnchor,
  IconArrowFork,
  IconArrowsDownUp,
  IconBadgeWc,
  IconBeach,
  IconBed,
  IconBuildingBridge2,
  IconBuildingCastle,
  IconBuildingStore,
  IconBuildingTunnel,
  IconBus,
  IconBusStop,
  IconCamera,
  IconChargingPile,
  IconChartBubble,
  IconCoffee,
  IconCornerRightDown,
  IconDiamond,
  IconFall,
  IconFishHook,
  IconFlag,
  IconFountain,
  IconHistory,
  IconHome,
  IconHomeDollar,
  IconHomeOff,
  IconIceCream2,
  IconInfoCircle,
  IconLadder,
  IconLeaf,
  IconMapPin,
  IconMapPinQuestion,
  IconMoodSmile,
  IconMotorbike,
  IconMountain,
  IconOvalVertical,
  IconPalette,
  IconPaperBag,
  IconParking,
  IconPennant,
  IconPool,
  IconRipple,
  IconRoute,
  IconSailboat,
  IconScubaDiving,
  IconScubaMask,
  IconShoe,
  IconSquare,
  IconStretching2,
  IconSwimming,
  IconToolsKitchen2,
  IconTower,
  IconTrees,
  IconTrekking,
  IconWalk,
  IconWall,
  IconWash,
  TablerIconsProps,
} from '@tabler/icons-react'
import { FC } from 'react'
import { IconName } from '~/server/db/constants/shared'

const iconsByIconName = {
  beach: IconBeach,
  flag: IconFlag,
  'scuba-mask': IconScubaMask,
  trees: IconTrees,
  'building-castle': IconBuildingCastle,
  'fish-hook': IconFishHook,
  fountain: IconFountain,
  mountain: IconMountain,
  ripple: IconRipple,
  parking: IconParking,
  history: IconHistory,
  trekking: IconTrekking,
  walk: IconWalk,
  'oval-vertical': IconOvalVertical,
  sailboat: IconSailboat,
  pennant: IconPennant,
  tower: IconTower,
  'home-off': IconHomeOff,
  home: IconHome,
  'building-tunnel': IconBuildingTunnel,
  'building-store': IconBuildingStore,
  'map-pin-question': IconMapPinQuestion,
  'charging-pile': IconChargingPile,
  motorbike: IconMotorbike,
  ladder: IconLadder,
  'building-bridge-2': IconBuildingBridge2,
  'scuba-diving': IconScubaDiving,
  fall: IconFall,
  'corner-right-down': IconCornerRightDown,
  wash: IconWash,
  wall: IconWall,
  anchor: IconAnchor,
  pool: IconPool,
  palette: IconPalette,
  camera: IconCamera,
  'paper-bag': IconPaperBag,
  'stretching-2': IconStretching2,
  square: IconSquare,
  'bus-stop': IconBusStop,
  'info-circle': IconInfoCircle,
  route: IconRoute,
  bus: IconBus,
  shoe: IconShoe,
  kayak: IconWalk,
  'arrows-down-up': IconArrowsDownUp,
  swimming: IconSwimming,
  diamond: IconDiamond,
  'chart-bubble': IconChartBubble,
  'arrow-fork': IconArrowFork,
  'map-pin': IconMapPin,
  'badge-wc': IconBadgeWc,
  leaf: IconLeaf,
  'tools-kitchen-2': IconToolsKitchen2,
  coffee: IconCoffee,
  'home-dollar': IconHomeDollar,
  bed: IconBed,
  'ice-cream-2': IconIceCream2,
  'mood-smile': IconMoodSmile,
} as const satisfies Record<IconName, Icon>

export const CategoryIcon: FC<
  TablerIconsProps & {
    icon?: IconName | null
  }
> = ({ icon, ...tablerIconsProps }) => {
  const iconWithoutFallback =
    icon && icon in iconsByIconName ? iconsByIconName[icon] : null
  const Icon = iconWithoutFallback ?? IconMapPin

  return <Icon {...tablerIconsProps} />
}
