import {
  Icon,
  IconAnchor,
  IconArrowBigDownLine,
  IconArrowsDownUp,
  IconBeach,
  IconBucket,
  IconBuildingBridge2,
  IconBuildingCastle,
  IconBuildingStore,
  IconBuildingTunnel,
  IconBus,
  IconBusStop,
  IconCamera,
  IconChargingPile,
  IconCornerRightDown,
  IconDiamond,
  IconFishHook,
  IconFlag,
  IconFountain,
  IconHistory,
  IconHome,
  IconHomeOff,
  IconIcons,
  IconInfoCircle,
  IconLadder,
  IconMapPin,
  IconMapPinQuestion,
  IconMotorbike,
  IconMountain,
  IconOvalVertical,
  IconPalette,
  IconPaperBag,
  IconParking,
  IconPennant,
  IconPool,
  IconRipple,
  IconRoute,
  IconSailboat,
  IconScubaDiving,
  IconScubaMask,
  IconShoe,
  IconSquare,
  IconStretching2,
  IconSwimming,
  IconTower,
  IconTrees,
  IconTrekking,
  IconWalk,
  IconWall,
  TablerIconsProps,
} from '@tabler/icons-react'
import { FC } from 'react'
import { IconName } from '~/server/db/constants/shared'

const iconsByIconName = {
  beach: IconBeach,
  flag: IconFlag,
  'scuba-mask': IconScubaMask,
  trees: IconTrees,
  'building-castle': IconBuildingCastle,
  'fish-hook': IconFishHook,
  fountain: IconFountain,
  mountain: IconMountain,
  ripple: IconRipple,
  parking: IconParking,
  history: IconHistory,
  trekking: IconTrekking,
  walk: IconWalk,
  'oval-vertical': IconOvalVertical,
  sailboat: IconSailboat,
  pennant: IconPennant,
  tower: IconTower,
  'home-off': IconHomeOff,
  home: IconHome,
  'building-tunnel': IconBuildingTunnel,
  'building-store': IconBuildingStore,
  icons: IconIcons,
  'map-pin-question': IconMapPinQuestion,
  'charging-pile': IconChargingPile,
  motorbike: IconMotorbike,
  ladder: IconLadder,
  'building-bridge-2': IconBuildingBridge2,
  'scuba-diving': IconScubaDiving,
  'arrow-big-down-line': IconArrowBigDownLine,
  'corner-right-down': IconCornerRightDown,
  bucket: IconBucket,
  wall: IconWall,
  anchor: IconAnchor,
  pool: IconPool,
  palette: IconPalette,
  camera: IconCamera,
  'paper-bag': IconPaperBag,
  'stretching-2': IconStretching2,
  square: IconSquare,
  'bus-stop': IconBusStop,
  'info-circle': IconInfoCircle,
  route: IconRoute,
  bus: IconBus,
  shoe: IconShoe,
  kayak: IconWalk,
  'arrows-down-up': IconArrowsDownUp,
  swimming: IconSwimming,
  diamond: IconDiamond,
} as const satisfies Record<IconName, Icon>

export const PlaceCategoryIcon: FC<
  TablerIconsProps & {
    icon?: IconName | null
  }
> = ({ icon, ...tablerIconsProps }) => {
  const iconWithoutFallback =
    icon && icon in iconsByIconName ? iconsByIconName[icon] : null
  const Icon = iconWithoutFallback ?? IconMapPin

  return <Icon {...tablerIconsProps} />
}
