name: Auto-assign issue or PR

on:
    issues:
        types: [opened]
    pull_request:
        types: [opened, edited, synchronize, reopened]
jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign issue or PR'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: mauriciabad
                  allowSelfAssign: false
