name: Deploy database migrations

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Deploy database migrations
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup pscale
        uses: planetscale/setup-pscale-action@v1

      - name: Get Deploy Requests
        if: github.event.pull_request.merged == true
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        run: |
          deploy_request_number=$(pscale deploy-request show descobreix-begur-app stage --org descobreix-begur-app -f json | jq -r '.number')
          echo "DEPLOY_REQUEST_NUMBER=$deploy_request_number" >> $GITHUB_ENV

      - name: Deploy schema migrations
        if: ${{ env.DEPLOY_REQUEST_NUMBER }}
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        run: |
          pscale deploy-request deploy descobreix-begur-app ${{ env.DEPLOY_REQUEST_NUMBER }} --wait --org descobreix-begur-app
